### PR TITLE
added Backup() to api

### PR DESCRIPTION
**Pull request by corndogcomputers**
see Backup.md

### CODE REVIEW

**Comment by corndogcomputers** [comment]
This is working well for me on an hourly basis. Needs more testing though.

**Comment by andrewsomething** [comment]
I haven't reviewed this closely, but one thing that jumps out at me is that it uses the `commands` module which is deprecated in Python 3. We've been trying to stay compatible with both 2 and 3.

From https://docs.python.org/2/library/commands.html

> Deprecated since version 2.6: The commands module has been removed in Python 3. Use the subprocess module instead.

**Comment by corndogcomputers** [comment]
Thank you. I will get this fixed and resubmit.

**Comment by koalalorenzo** [comment]
My suggestion would be to start from the tests and the update/create modules. I see that there are some lines that I would like to change to make it more KISS :-) ( I will probably comment the code directly )

**Comment by koalalorenzo** [comment]
@corndogcomputers This update is really interesting, but probably the command line/script is not fitting the purpose of the repository: you should create another project/repository for the command line! That would be the best solution. Consider also to use 4 space indentation and to not go over the 80th column in the file. :page_facing_up:

**Comment by corndogcomputers** [comment]
Agreed. It would be better to separate the backup script to it's own project. I would however like to keep contributing to this project as well. Thanks so much for the advice. I'm pretty new to Python so I have a lot to learn.

**Pull request closed without merging**
