### PR TITLE
Fix copy&pasto in docstrings

### PR DESCRIPTION
**Pull request by tc-ubnt**

### CODE REVIEW

**Comment by koalalorenzo** [comment]
Thank you, Not really a big change

**Comment by tc-ubnt** [comment]
Indeed just a small change. Yet you won't take it and keep it broken instead. I'm glad I didn't start anything bigger ;)

**Comment by wacuuu** [comment]
@koalalorenzo what prevents you from merging this?

**Comment by koalalorenzo** [comment]
I find it weird and constant "contributors" that are just changing few line of code that are not really adding any value. The reaction that @tc-ubnt had is a clear sign to me.

**Comment by tc-ubnt** [comment]
Thanks for your explanation, let's not waste more time here.

**Pull request closed without merging**
