### PR TITLE
support requests <2.4.2

### PR DESCRIPTION
**Pull request by tomscytale**
tests pass using requests==2.2.1 and requests==2.5.1

i'm still testing this against the real DO API

### CODE REVIEW

**Comment by tomscytale** [comment]
#88

**Comment by koalalorenzo** [comment]
Tests seems to pass correctly.

**Comment by koalalorenzo** [comment]
@andrewsomething is this working for you too? In that case we can merge this!

**Comment by andrewsomething** [comment]
:+1: Looks great, and pass on 14.04 w/ requests < 2.4.2

Thanks for humoring me! I really appreciate it.

**Comment by koalalorenzo** [comment]
Great guys! :+1:

**Pull request merged**
