### PR TITLE
Added update_domain_record and delete_domain_record  API methods

### PR DESCRIPTION
**Pull request by makov44**

### CODE REVIEW

**Comment by koalalorenzo** [comment]
Hello!
Thanks for your contribution, but there are no tests that are validating and verifying your changes.
Please update the PR with more tests

**Comment by makovskyy** [comment]
> Hello!
> Thanks for your contribution, but there are no tests that are validating and verifying your changes.
> Please update the PR with more tests

Hello,
I was using this package in production and I had no issues. I would say the functional test completed.

**Comment by koalalorenzo** [comment]
That is nice, but we need tests :-)
Please add more tests that are validating your code

**Comment by Icukurra** [comment]
These methods are so foundational to general domain maintenance that I'm surprised they weren't created the first go around. And now won't be included after a year because no one wants to write a test for it? Shame.

**Comment by koalalorenzo** [comment]
> These methods are so foundational to general domain maintenance that I'm surprised they weren't created the first go around. And now won't be included after a year because no one wants to write a test for it? Shame.

@Icukurra Let me know if you need help in opening a PR (forking this one)

**Comment by new-guy** [comment]
Added tests in #332

**Pull request merged**
