### PR TITLE
Readme changes

### PR DESCRIPTION
**Pull request by cprogrammer1994**
- [x] rst for PyPI
- [x] fixed missing iframes

**Note:**
MD files are not supported on PyPI :disappointed:
[pypi.python.org/pypi/python-digitalocean](https://pypi.python.org/pypi/python-digitalocean)

rst:
- created using [Pandoc](http://pandoc.org/)
- tested with [rst.ninjs.org](http://rst.ninjs.org/)

### CODE REVIEW

**Comment by koalalorenzo** [comment]
can you rebase your changes with the latest version of master?

**Comment by cprogrammer1994** [comment]
Not sure how to do it since the fork is "old"
Is that a git pull from a different origin?

**Comment by koalalorenzo** [comment]
Yes, you can do it from a different origin: fetch all, pull the master from the original origin, then rebase on top of that

(Note: I just wanted to write "original origin" 😆 )

**Comment by cprogrammer1994** [comment]
reverted commit fights back (don't merge yet)

**Comment by koalalorenzo** [comment]
I will wait for a "OK" message to review and then merge this :)

**Comment by koalalorenzo** [comment]
@cprogrammer1994 Is this PR ready?

**Comment by cprogrammer1994** [comment]
**yes**, the diff looks great.

**Pull request merged**
