### PR TITLE
Fixes for tests and ssh_key parameter

### PR DESCRIPTION
**Pull request by tomscytale**

### CODE REVIEW

**Comment by tomscytale** [comment]
This was added in d428dac3a6912cbc1a3d9b8483e26a674c6e761d - "ssh_keys must be an array"

I don't understand how appending '[]' to the key name helped? Is this some kind of convention used by the requests library when adding URL query paramaters?...

looks like it is: http://stackoverflow.com/a/23347265/473285
new one to me - and I'm not a novice at this kind of thing. 

looks like this commit is needed if we use JSON data instead of url query paramaters

**Comment by tomscytale** [comment]
This appears to be the only place in the project where '[]' is appended to a param name

**Comment by koalalorenzo** [comment]
Is it working properly by removing the [] from the param name for you? I remember that this was causing a problem in past.

**Comment by tomscytale** [comment]
yes - it works fine now

the `[]` is necessary when submitting a list as a value in the query paramaters - it's a little-known corner of http - see http://stackoverflow.com/a/23347265/473285 or http://docs.python-requests.org/en/latest/user/quickstart/#passing-parameters-in-urls

now that we are using JSON we need to remove the `[]`

**Comment by tomscytale** [comment]
All tests pass with both Python2.7 and Python3.4

**Comment by koalalorenzo** [comment]
Amazing! Thanks :+1:

**Pull request merged**
