### PR TITLE
Add CDN Endpoint API to create, update and delete.

### PR DESCRIPTION
**Pull request by ajite**
Updated manager to do not submit body params during request when params argument was set to False.

```
        if params is False:
            del kwargs['data']
```

The API will return an error when submitting params (even empty).

The default behaviour sets the “params" to an empty dict when its value is equal to None.

```
        if params is None:
            params = dict()
```

This does not work with the CDN Enpoints API. I did not want to change this behaviour since it was probably made because other API endpoints needed a body (even if empty).

I am aware that is not the most elegant solution though.

### CODE REVIEW

**Comment by koalalorenzo** [comment]
Interestingly, no workflow started :O I'll look into it so that tests will work

**Comment by koalalorenzo** [comment]
@ajite could you try adding a commit that would trigger the tests again? 🤔

**Comment by ajite** [comment]
Hi,

I merged the main branch new content to my PR. It seems to have triggered github actions. 
I wrote that PR a while ago, I am not sure how relevant it still is.

**Review by koalalorenzo — APPROVED** [review]
LGTM! Thx for contributing! :)

**Pull request merged**
