### PR TITLE
Update Droplet.__get_ssh_keys_id_or_fingerprint for backwards compatibility with Python 3 (Fixes #80)

### LINKED ISSUE #80: long and unicode not defined in python 3
Since python 3 is supported, it should be noted that long and unicode are not defined in python 3 (u'string literal' still works). This is a problem for __get_ssh_key_id_or_fingerprint in Droplet. A possible solution would be

           try:
                inttype = [int, long]
                strtype = [str, unicode]
            except NameError:
                inttype = [int]
                strtype = [str]

By the way, many of the unit tests fail on python 3.

### PR DESCRIPTION
**Pull request by moyamo**
Add try-except to ignore unicode or long if it does not exist.

### CODE REVIEW

**Comment by koalalorenzo** [comment]
Amazing, I was fixing it without catching an error. See 3a02812647f12e69254fc41df3209b895b6ee277

**Comment by moyamo** [comment]
That's a cool trick. Doesn't fix [int, long] though.

**Comment by moyamo** [comment]
You could probably do something similar [int, type(2**64)]

**Comment by koalalorenzo** [comment]
Check the code and update your branch please. I already fixed this in https://github.com/koalalorenzo/python-digitalocean/commit/3a02812647f12e69254fc41df3209b895b6ee277

**Pull request closed without merging**
