### PR TITLE
Add rules manager to exiting firewall

### PR DESCRIPTION
**Pull request by sajadbahar**
Implement inbound and outbound rule management to exiting firewall

### CODE REVIEW

**Comment by koalalorenzo** [comment]
Please add Tests for each new functionality!

**Comment by prasket** [comment]
@narsic any word on getting this PR fixed up and submitted?

**Review by koalalorenzo — CHANGES_REQUESTED** [review]
More tests needed

**Comment by aliasifk** [comment]
@koalalorenzo Can you please merge the changes

**Pull request merged**
