### PR TITLE
Add support for floating IPs

### PR DESCRIPTION
**Pull request by andrewsomething**
https://www.digitalocean.com/company/blog/floating-ips-start-architecting-your-applications-for-high-availability/

### CODE REVIEW

**Comment by koalalorenzo** [comment]
It sounds cool! I will wait for the tests to complete and then check int.
I hope to publish this ASAP. Thanks!!!

**Comment by koalalorenzo** [comment]
It seems good to me :+1:

**Comment by andrewsomething** [comment]
Awsome! Thanks koalalorenzo!

**Comment by koalalorenzo** [comment]
Thank you for your support! :+1:

**Comment by devries** [comment]
Wow, I just wanted to say that is some amazing hustle at getting this updated for a brand-new feature. Thank you for your hard work.

**Pull request merged**
