### PR TITLE
Project API

### PR DESCRIPTION
**Pull request by smtydn**

### CODE REVIEW

**Comment by wacuuu** [comment]
Nice :) But please add some description to PR

**Comment by smtydn** [comment]
ive created a new class 'Project' for digitalocean api - projects. i also created new method for Manager to get all projects and its test

**Comment by wacuuu** [comment]
You would like to have this merged as is or you want to develop further, and have for example methods for project creation?

**Comment by smtydn** [comment]
for now, i prefer it to be merged. maybe later i can help it to develop further.

**Comment by koalalorenzo** [comment]
Closed in favour of #300

**Pull request closed without merging**
