### PR TITLE
Added more missing methods to manager

### PR DESCRIPTION
**Pull request by tallus**
- added snapshot methods to manager
        - get_snapshot
        - get_all_snapshots
        - get_droplet_snapshots
        - get_volume_snapshots
        - tests
    - removed unused import
    - s/function/method/ in doc strings
    - reordered methods for consistency, alphabetized by purpose

### CODE REVIEW

**Comment by koalalorenzo** [comment]
Next time: use multiple commits for each change, it is impossible to review without checking what changed since you re-ordered everything! With multiple commits we have an easier way of doing reviews. Now it is just a mess

**Comment by koalalorenzo** [comment]
Can you also update the branch?

**Comment by koalalorenzo** [comment]
@andrewsomething what do you think?

**Comment by tallus** [comment]
On May 2, 2017 10:53:46 PM PDT, Lorenzo Setale <notifications@github.com> wrote:
>@andrewsomething what do you think?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/koalalorenzo/python-digitalocean/pull/200#issuecomment-298828542

Sorry, I've been wrapped up in something else. I hope to get to it in the next couple of days.

**Comment by tallus** [comment]
See #203 for revised pull request

**Pull request closed without merging**
