### PR TITLE
Make endpoint url configurable #267

### PR DESCRIPTION
**Pull request by davitovmasyan**
#267

### CODE REVIEW

**Comment by wacuuu** [comment]
Let me speed up review a bit for you: this for sure will come back as 'needs work', because you are missing tests for this :) If you don't belive me, open PR and see why most of them is stuck

**Comment by davitovmasyan** [comment]
@wacuuu will add tests soon!

**Comment by davitovmasyan** [comment]
@wacuuu any suggestions on how to mock `os.environ` in python2?

**Comment by davitovmasyan** [comment]
@wacuuu done! Any other comments?

**Comment by wacuuu** [comment]
Not sure, but I think it would be nice to mention it somewhere in readme, so that potentially interested person knows right away that this is compatible with other providers.

**Comment by davitovmasyan** [comment]
@wacuuu docs are ready too!

**Comment by wacuuu** [comment]
Really nice. But as far as I understand, this will also work if you pass end_point as constructor argument. Please mention that too. I think you can mention it in first example in docs, listing all droplets that is.

**Comment by davitovmasyan** [comment]
@wacuuu done, any other comments?

**Comment by wacuuu** [comment]
Looks ok for me, but bare in mind that @koalalorenzo has to review it :)

**Pull request merged**
