### PR TITLE
Tag unittest

### PR DESCRIPTION
**Pull request by moeseth**
Hello, I have written test cases and tested on my live digital ocean account and it all worked perfect.

Please review and pull soon.

Have a great day.

### CODE REVIEW

**Comment by koalalorenzo** [comment]
Can you update/rebase your branch? I have merged the other PR ( #137 ) so you can merge this.

**Comment by koalalorenzo** [comment]
I am still not able to merge this. Can you merge the master into your branch, resolve the conflicts and push?

**Comment by moeseth** [comment]
@koalalorenzo I pushed another merge. I'm new to rebasing. Sorry for the mess.

**Comment by koalalorenzo** [comment]
No problem! You did a good job :) 👍  Thanks for helping!

**Comment by moeseth** [comment]
@koalalorenzo no problem, would love to see these Tag feature in pip package version 1.9.1 👍

**Comment by koalalorenzo** [comment]
@moeseth tonight :)

**Comment by moeseth** [comment]
@koalalorenzo did you happen to update it? :)

**Comment by koalalorenzo** [comment]
This evening (CET) ;-)

**Comment by moeseth** [comment]
@koalalorenzo 👍

**Comment by koalalorenzo** [comment]
No joking, I had no electricity and no internet yesterday evening :( Sorry for the delay! Hopefully I will have it back tonight!

**Pull request merged**
