### PR TITLE
Fix for #178

### PR DESCRIPTION
**Pull request by caseyhen**

### CODE REVIEW

**Comment by andrewsomething** [comment]
Thanks for this! It would be great to fix up the tests as well. We test the contents of the request here:

https://github.com/koalalorenzo/python-digitalocean/blob/master/digitalocean/tests/test_droplet.py#L807

**Comment by koalalorenzo** [comment]
@caseyhen if you can fix the tests it will be merged! Thank you so much for your help!

**Comment by caseyhen** [comment]
@andrewsomething @koalalorenzo I've added the ability for tags on `create_multiple()` and updated the tests. Take a look and let me know.

**Comment by koalalorenzo** [comment]
@caseyhen can you check and resolve the conflicts?

**Comment by caseyhen** [comment]
@koalalorenzo All taken care of.

**Comment by koalalorenzo** [comment]
Awesome! Thanks for helping! :-)

**Pull request merged**
