### PR TITLE
Add constants for the region slugs

### PR DESCRIPTION
**Pull request by BenMusch**
I think it'd be nice to have some constants to avoid magic strings. I'm unsure what the correct naming convention would be for the regions (e.g. should it be `SFO1`? `SFO_1`? `SAN_FRANSICO_1`?)

Let me know what you think about this idea

There can also be validation of input against these constants, but I'm not sure whether there should be too much validation by this library, rather than leaving it to the api.

### CODE REVIEW

**Comment by koalalorenzo** [comment]
The main purpose of this project is to keep things as similar as possible to the API interface, but providing it via classes. Do you think this is following that idea? How do we maintain these constants?

**Comment by BenMusch** [comment]
@koalalorenzo I agree that there didn't really seem like a way to add this to the project that fit its current structure -- maybe it'd make sense to completely separate the constants into some sort of helper module? i.e.:

```python
from digitalocean.constants import regions

regions.NYC1
> "nyc1"
```

And at that point, the configuration could even be extracted into some JSON/YAML file and then just loaded in a python module

**Comment by koalalorenzo** [comment]
I would like to avoid any kind of constants that are related to options passed to the API, otherwise we have to maintain them... even if loaded from a JSON and added into a module (Somebody still should run that process every time there is a change).

**Comment by BenMusch** [comment]
@koalalorenzo Gotcha -- I think it's worth just closing this PR then, since I can't think of a good way to fit these constants into the structure of the library without some other negative consequence

**Pull request closed without merging**
