### PR TITLE
Implement the firewall rules management 

### PR DESCRIPTION
**Pull request by aliasifk**
Can add/remove outbound and inbound rules

### CODE REVIEW

**Comment by aliasifk** [comment]
@koalalorenzo Can you please merge

**Comment by scy** [comment]
@aliasifk I have contributed one single PR to this project back in 2020, and yet you’ve contacted me via email & LinkedIn in order to get this PR reviewed.

Please don’t do that. I’m not sure whether getting your PR reviewed by random people on the internet will result in it being merged any faster. But also, nagging folks via email and social media is frowned upon and they’re more likely to consider you a nuisance than actually helping you out.

Also, your PR is only 4 days old. This is an open source project, people maintain it in their spare time. It can take weeks or months for things to get merged. If you need the feature you’ve added sooner, consider using your fork instead.

**Comment by aliasifk** [comment]
I am really sorry that I disturbed you, I had no intentions of doing it.I am relatively new to PRs and I did not knew It took time and was excited enough to email. I just looked at your profile and sent a connect on linkedIn not because I wanted you to PR . I also did not mail “folks” just you and the owner of repo.You because I saw your name in the repo.Once again, sorry. From: Tim WeberSent: Monday, October 3, 2022 3:23 PMTo: koalalorenzo/python-digitaloceanCc: Ali Asif Khan; MentionSubject: Re: [koalalorenzo/python-digitalocean] Implement the firewall rules management (PR ***@***.*** I have contributed one single PR to this project back in 2020, and yet you’ve contacted me via email & LinkedIn in order to get this PR reviewed.Please don’t do that. I’m not sure whether getting your PR reviewed by random people on the internet will result in it being merged any faster. But also, nagging folks via email and social media is frowned upon and they’re more likely to consider you a nuisance than actually helping you out.Also, your PR is only 4 days old. This is an open source project, people maintain it in their spare time. It can take weeks or months for things to get merged. If you need the feature you’ve added sooner, consider using your fork instead.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by koalalorenzo** [comment]
Thank you for your contribution, it is appreciated. Though, do not reach out to us privately insisting on getting a review. We are not getting paid for this project. As I told you, sadly I have very little time on my hands and bugging people around is not helping making the process easier.

I will evaluate this PR later when I will have time.

**Comment by koalalorenzo** [comment]
@aliasifk I can see that the code is very much looking like #244 but with the addition of the tests.

What I can see is that part of your code looks copied, pasted and "re-authored", and instead of rebasing it and attributing code ownership to @sajadbahar, it has been re-written. It would be nice to see your code, rebased on top of #244 so that both you (@aliasifk) and @sajadbahar will be seen as contributors, instead of just you. 

A good suggestion for OSS contribution is to not steal other people code and rebrand it as yours! 😅 Unless you and @sajadbahar are the same person/legal identity! 🤣 

What I would suggest is one of the following:

* Open a new PR that includes contributions from both you and @sajadbahar 
* Force push / rewrite history of this PR to include his commit history
* Add your commits to his PR if possible

Probably the first option would be ideal! 💪 Please let me know and thank you again for your help with the tests! 😄

**Comment by aliasifk** [comment]
@koalalorenzo Thanks, yes I first saw the PR that he has done and definitely copied those methods and added the test cases, because I thought the PR to be too old and did not saw any further comments from their side when you had suggested changes to add test cases
So I decided to create a new PR.
But let me see if I can reach out to him or perhaps do something to involve his contribution, among the options you have suggested

**Comment by sajadbahar** [comment]
@aliasifk I have rebased my fork with the master and it's good to go, you could get the latest code and create PR with your change on top of #244 

@koalalorenzo Thanks for your comment 

PS: Don't copy and paste someone's code and make it yours

**Comment by aliasifk** [comment]
@sajadbahar I don't understand sorry, can you tell me how I can push commits that include tests in your PR #244

**Comment by aliasifk** [comment]
Ok I have created a new PR, did not knew this was actually possible on github.

**Pull request closed without merging**
