### PR TITLE
Allow additional create() API parameters

### PR DESCRIPTION
**Pull request by Leonid99**

### CODE REVIEW

**Comment by koalalorenzo** [comment]
I personally would suggest to avoid errors catching.
what about something like this:

```python
if "addl_opts" in kwargs.keys():
    addl_opts =  kwargs["addl_opts"]
    for addl_opt in addl_opts:
        data[addl_opt] = addl_opts[addl_opt]
```

**Comment by Leonid99** [comment]
You are right, it looks nicer. Fixed.

**Comment by koalalorenzo** [comment]
@Leonid99 can you provide me a link where it is explained the usage of these new values in the API?

**Comment by domrhines** [comment]
@koalalorenzo There are no new values at DigitalOcean as of now. @Leonid99 is adding this as support for potential new features at the company so that features in the REST api can be tested quickly before making them permanently exposed in libraries like yours and libcloud and so forth.

**Comment by koalalorenzo** [comment]
I am confused, and I don't want other developers confused. This seems to be something internal for "the company", not something that we may want to publish. This may allow users to use custom properties that are "secret" and maybe open DO API to vulnerabilities in case "something forgotten" or "undocumented" is used. 

I don't think we should merge, I think you should keep this in a different branch for your own development and testing.

**Comment by domrhines** [comment]
That's incorrect. We release new products all year that are ahead of these bindings. I don't see the confusion at all. It would be in user's best interest to have the flexibility to temporarily exercise unexposed parts of our REST api when a product is released without having to completely and unnecessarily re-run $pip install or $ apt-get install until the new version of the bindings is released.

In fact, I think it would be a little short-sited for a set of bindings not to take this into consideration and would in fact lower the adoption of the bindings.

**Comment by koalalorenzo** [comment]
> It would be in user's best interest to have the flexibility to temporarily exercise unexposed parts of our REST api when a product is released without having to completely and unnecessarily re-run $pip install or $ apt-get install until the new version of the bindings is released.

I highly disagree, this would lead the project to bigger problems since developers should use specific versions to implement specific rules and method based on their needs. For example, If this changes is applied, then they will not update when the third version will be released and the old API deprecated, and nobody will contribute... since "one line of code can change it".

If a deeper implementation is missing, like #132 for example, people edit the open source code and a new minor version for everybody needs is released! That is the spirit.

Allowing users to use custom options out of the blue is just a bad idea, for the library (to allow users to use the version they want, and keep the module updated) and to avoid security problems. At the moment, I am not going to merge this since I think "Your Company" (I still don't know who you are, since your profiles are empty, _are you working at DO?_ ) would be the only one using this... and if developers can "just modify the behavior" without updating and contribute with the others, it's just a big loss for the development process of this module. :cry:

**Comment by domrhines** [comment]
Yes, we both work for DO: http://michael.hinespot.com 

I clearly said we release a lot of new products, and I pretty clearly said temporarily and flexibly ---- nowhere did I say permanently.

I'm pretty sure developers are smart enough to know not to depend on temporary parts of a binding and to be smart enough to follow our company's REST api without assuming the bindings know what they're doing.

I don't believe anybody uses bindings as the ultimate source of truth --- and if they are, they shouldn't be using bindings in the first place.

**Comment by koalalorenzo** [comment]
> Yes, we both work for DO: http://michael.hinespot.com
Good to know! Update and write something on your GitHub Profile that you created... yesterday! :smile: It seems scammy!  

> I'm pretty sure developers are smart enough to know not to depend on temporary parts of a binding and to be smart enough to follow our company's REST api without assuming the bindings know what they're doing.
Trust me on this: if you are following the Bitcoin community, this is a similar situation to a Soft Fork vs Hard Fork.

BTW, if you need this fix for your own development, the use your own internal development branch! :wink: If you are willing to implement new things, improve the code, or update the API bindings to the new released version, I will be more than happy to review and merge it.

[Bitcoin Joke] ...but I don't allow soft forks on this repo! :lollipop:

**Comment by domrhines** [comment]
I created this github profile using my company email address precisely for the purposes of proving that I have a company email address instead of using my primary email address, assuming that you would take it upon yourself to check my email address.

As I have said twice before, this fix is *not* for our own development -- perhaps that point was lost in the last two posts, and I'm not sure why you keep repeating it. The company has released and will continue to release new products, and users are testing our REST api all the time. They should not need to be held hostage for an unknown amount of time waiting for a set of bindings to support them and if they have a proper CI process built into their software, they should also be prepared enough to use the correct set of the bindings when support is finally released.

If you have a better idea on how to achieve the same goal (specifically passing parameters to our API that your library does not yet know about), we're more than open to suggestion.

**Comment by domrhines** [comment]
(I didn't realize github email addresses were hidden by default ----- just fixed that.)

**Comment by koalalorenzo** [comment]
> They should not need to be held hostage for an unknown amount of time waiting for a set of bindings to support them and if they have a proper CI process built into their software, they should also be prepared enough to use the correct set of the bindings when support is finally released.

I totally see your point, but I will never implement something that is not yet released. Developers should not use API in production that are not released yet. I prefer to update the library and the developers then can update their versions if they need to... that takes time but it is the best way to have stable software. 

Do you have CI process that needs this implemented?

**Comment by koalalorenzo** [comment]
I still see that this would ruin the development process of this project, so people will stop contributing and they will just "hot-fix" to implement something by their own, without sharing it with the rest of us. This fix is not how OSS works.

**Comment by domrhines** [comment]
>  Developers should not use API in production that are not released yet. 

That's not true. All companies, including ours have beta releases. We have them all the time.

> I still see that this would ruin the development process of this project, so people will stop contributing and they will just "hot-fix" to implement something by their own, without sharing it with the rest of us. This fix is not how OSS works.

Nobody who "seriously" uses our API or any other API for that matter should be relying purely on a set of bindings to decide how OSS works. I don't think an OSS discussion needs to be a part of this particular issue. OSS is a long, complicated subject that's open to debate for another day and another time.

**Comment by koalalorenzo** [comment]
> That's not true. All companies, including ours have beta releases. We have them all the time.
IMHO Developers should not use Beta releases in production for Obvious reasons. 

If you, as DO, want these kind of changes and impose specific directory you should consider to hire developers to maintain and develop seriously the official python version. The reason why this is the most used python interface to your API is because it was developed as OSS, and amazing people like @andrewsomething, @tomscytale and other contributors, helped me to implement features that everybody needs. I sadly admit that I had no time to keep this project up to date, but this is not an excuse to allow "on-the-fly" fixes and **stop the contributions**.

Let me try to use other words to explain better: these changes will **allow developers to skip the "updated version"** as you said, and Digital Ocean developers can use it to test "new options". With this fix only developers' own code will receive changes, instead python-digitalocean code will easily stop receiving contributions to the project, since nobody will share new ways to improve it and implement new APIs or options.

Because I am not working full time on python-digitalocean or any DO's project, ans also _since Digital Ocean decided to remove the credits that I got as a prize for this project_, merge this would kill python-digitalocean since **nobody will take care of it**. I am worried about it. I think **this repository is an example of good OS development** and without our contributions the python implementation of Digital Ocean's API would have been stuck to the old API v1. 

I might change my idea, but at the moment this will not be implemented.

**Comment by domrhines** [comment]
I guess we've reached an impasse. Good luck then.

**Pull request closed without merging**
