### PR TITLE
Changes in init to make documentation aligned with code

### PR DESCRIPTION
**Pull request by wacuuu**
Changing __init__.py so that imports and docs have the same path.
For example:
old way:
import digitalocean
digitalocean.ForwardingRule()
new way:
import digitalocean
digitalocean.LoadBalancer.ForwardingRule()

### CODE REVIEW

**Comment by koalalorenzo** [comment]
Why this change was needed? all the docs now should be updated.

Am I wrong?

**Comment by wacuuu** [comment]
I do this mainly because time i spent when using this lib on my project i had to keep on digging to make forwarding rule. You see example from my commit message; i tried to do the new way, because if you make html docs you see this:
image
And this is very misleading

**Comment by wacuuu** [comment]
Ok, I'm done with my part I think. How do you like it with all tests working?

**Comment by koalalorenzo** [comment]
What I am worried is that this is a breaking change with people that are currently working and have already implemented the apis. What do you think about that?

**Comment by wacuuu** [comment]
Yep, I agree. This would have to be rolled out as a major then. But what also crossed my mind, maybe it would be good to postpone this and work on domain update too, so the new release wouldn't just mess other peoples code, but also introduce something.

Anyway, I do acknowledge consequences for old users, but I think this change clears up a problem for new ones(mismatch with documentation) and leaves much more space for decent development for future.

**Comment by koalalorenzo** [comment]
Closing for now. We can focus on new features and different issues.

Thank you a lot anyway!!! 😃

**Comment by wacuuu** [comment]
If you decided to merge this or consider at some point, I moved changes to imports_fix branch on my fork

**Pull request closed without merging**
